group_header_array = ["ID",
                      "Main Keyword",
                      "Variation",
                      "Common Links",
                      "Volume",
                      "Primary Intents",
                      "Secondary Intents",
                      "Client Ranking URL",
                      "Client Ranking Position",
                      "Client URL Ranking Count",
                      "CPC",
                      "Variant Count",
                      "Difficulty",
                      "Average MK KD",
                      "Current Traffic",
                      "Potential Traffic",
                      "Current Value",
                      "Potential Value",
                      "Value Delta",
                      "Average Rank",
                      "Sum Values",
                      "Percentage Ranking",
                      "Value Opportunity",
                      "Volume Opportunity",
                      "Topic Volume",
                      "Percentage Volume",
                      "Quartile of Volume",
                      "Avg Rank Quartile 4",
                      "Priority Score",
                      "Auto Mapped URL",
                      "Potential Content Gap",
                      "Total Content Gap",
                      "Keyword Gap",
                      "Potential Cannibalization"]
sub_group_header_array = ["ID",
                          "Main Keyword",
                          "Variation",
                          "Common Links",
                          "Sub Group",
                          "Volume",
                          "Primary Intents",
                          "Secondary Intents",
                          "Client Ranking URL",
                          "Client Ranking Position",
                          "Client URL Ranking Count",
                          "CPC",
                          "Variant Count",
                          "Difficulty",
                          "Average MK KD",
                          "Current Traffic",
                          "Potential Traffic",
                          "Current Value",
                          "Potential Value",
                          "Value Delta",
                          "Average Rank",
                          "Sum Values",
                          "Percentage Ranking",
                          "Value Opportunity",
                          "Volume Opportunity",
                          "Topic Volume",
                          "Percentage Volume",
                          "Quartile of Volume",
                          "Avg Rank Quartile 4",
                          "Priority Score",
                          "Sub Group Volume",
                          "Auto Mapped URL",
                          "Potential Content Gap",
                          "Total Content Gap",
                          "Keyword Gap",
                          "Potential Cannibalization"]
default_grouping_threshold = 3
default_sub_grouping_threshold = 6
fuzzy_match_threshold = 89
