# Generated by Django 3.2.4 on 2021-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinedjobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedjob',
            name='search_engine',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
